### ISSUE TITLE
Setting exposure time

### ISSUE THREAD

**Issue by steveschulze** [bryanmiller/gsselect#1]
Hi,

is it possible to set the exposure times, too?

Cheers,

Steve

**Comment by bryanmiller** [comment]
Hi,

Unfortunately not with the current API. You would need to define different templates with different exposure times.

Cheers,
Bryan

**Comment by steveschulze** [comment]
Hi Bryan,

OK, thanks a lot.

Cheers,

Steve

**Comment by steveschulze** [comment]
Hi Bryan,

OK, thanks a lot.

Cheers,

Steve
